force-app/main/default/objects/DialShree_UserInfo__c/DialShree_UserInfo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DialShree UserInfo</label>
</CustomObject>

force-app/main/default/objects/DialShree_UserInfo__c/fields/Dialshree_Password__c.field-meta.xml
<CustomField>
    <fullName>Dialshree_Password__c</fullName>
    <label>Dialshree Password</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DialShree_UserInfo__c/fields/Dialshree_User__c.field-meta.xml
<CustomField>
    <fullName>Dialshree_User__c</fullName>
    <label>Dialshree User</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DialShree_UserInfo__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <label>Salesforce User</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DialShreeApiTest.cls
/* 
    Class Name :  DialShreeApi 
    Code-Covege : 77%
*/

@isTest
public class DialShreeApiTest {
    @isTest
    public static void testCustomData() { 
        // Create Custom setting record 
        DialShree_UserInfo__c dialUser = new DialShree_UserInfo__c();
        dialUser.Name = UserInfo.getUserName();
        dialUser.Dialshree_User__c = 'Test' + DateTime.now();
        dialUser.Dialshree_Password__c = 'TestPwd';
        dialUser.Salesforce_User__c = UserInfo.getUserName();        
        insert dialUser;
        System.assertEquals(dialUser.Dialshree_Password__c,'TestPwd','');

        DialShreeApi.getServiceSettings();
        DialShreeApi.dialUserInfoCs();      
        DialShreeApi.apiWrapperList();     
    }
}